### ISSUE TITLE
`spago test` errors when there are no tests

### ISSUE THREAD

**Issue by elliotdavies** [spacchetti/spago#383]
Running `spago test` on a project where there isn't a `test` directory results in this error:

```
Installation complete.
purs compile: No files found using pattern: test/**/*.purs
Build succeeded.
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '../output/Test.Main'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/elliot/<filepath elided>/.spago/run.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
spago: Tests failed: 1
```

I think this should probably either succeed (because in effect 0/0 tests passed) or fail in a nicer manner.

**Comment by f-f** [comment]
This is definitely good, but how would we detect this?

The implementation for `spago test` is just calling the `Test.Main` module with node, so to detect there's no such module we should somehow find out about all the modules in the included sources?
A low-tech approach would be full-text search on all the files searching for the string `module Test.Main`, but at that point we might as well just implement a parser.. (which we could also use for #165)
